# Site settings
title: "Today I learn a new thing"
description: "just a small blog about some technical collection :sweet grinning:"

email: "kietnvt.it@gmail.com"
url: "https://tuankiet.github.io"
twitter_username: "nvtkiet"
github_username:  "tuankiet"

# Header Links
github:
  is_project_page: true
  repository_name: "Blog"
  project_tagline: "Blog"
  github_profile: "https://github.com/tuankiet"
  owner_url: "https://github.com/tuankiet"
  repository_url: "https://github.com/tuankiet/tuankiet.github.io"
  owner_name: "Tuan Kiet"

# Build settings
markdown: kramdown

paginate: 20
paginate_path: "/blog/page:num/"

theme: jekyll-theme-modernist

